//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleCategoryInt
    {
        public string Id { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string ArticleId { get; set; }
        public string CategoryId { get; set; }
        public bool IsRemoved { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Category Category { get; set; }
    }
}
