//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public string Id { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string Content { get; set; }
        public string CommentId { get; set; }
        public string UserId { get; set; }
        public string ReplyToUserId { get; set; }
        public bool IsRemoved { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
